server {
    listen 80;
    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    # Static assets dari folder client
    location /assets/ {
        alias /usr/share/nginx/html/client/assets/;
        expires 1y;
        add_header Cache-Control "public, immutable";
    }
}